### ISSUE TITLE
research book crashes game

### ISSUE THREAD

**Issue by StepOnShadows** [syndicate25/ProgSurv#2]
[crash-2022-10-06_12.01.39-client.txt](https://github.com/syndicate25/ProgSurv/files/9720532/crash-2022-10-06_12.01.39-client.txt)
clicking on knowledge talismans in the research book crashes the game, consistent happens every time

**Comment by syndicate25** [comment]
I'll see if I can figure out the problem, but I want to say that one was a known issue with Minefantasy2.. 

I'll get back to you on this one.

**Comment by syndicate25** [comment]
Okay, so that page isn't populating (and won't) because I have disabled skill book crafting.  You have to find the books, instead of making them yourself to basically skip a whole bunch of progression in that mod, which seemed cheaty and cheap, so it's staying off.  From what I understand, that tab relies on those recipes being available, but they're not (due to the config change), and since it doesn't know how to handle that, it just crashes the game.

I don't think those are used for anything other than making skill books, so I'll probably remove them from the pack entirely in a future update, if that's the case.

The other option I am considering, just so the tab works, is enable crafting, but manually disable the recipes instead.  That seems misleading though since the research book will still show them as craftable/how to craft them.

I'll figure out what I'm going to do with it and surprise you in the next update! ;)

**Comment by syndicate25** [comment]
Decided to change the heading for the Talisman section of the book to indicate that it will crash the game, and that it has been disabled.  There was no option to remove the crafting recipes aside from disabling the module, which is what is causing the crash.
